version: 2

references:
  circleci_docker_primary_tf11: &circleci_docker_primary_tf11 trussworks/circleci-docker-primary:0f54e1d0b033fd7639ae287ecd4445b4aa9bd37a
  circleci_docker_primary_tf12: &circleci_docker_primary_tf12 trussworks/circleci-docker-primary:tf12-0f54e1d0b033fd7639ae287ecd4445b4aa9bd37a

jobs:
  validate:
    docker:
      - image: *circleci_docker_primary_tf12
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache

  terratest-tf11:
    docker:
      - image: *circleci_docker_primary_tf11
    steps:
      - checkout
      - run:
          name: Run terratest
          command: go test -v ./test/...

  terratest-tf12:
    docker:
      - image: *circleci_docker_primary_tf12
    steps:
      - checkout
      - run:
          name: Run terratest
          command: go test -v ./test/...

workflows:
  version: 2
  validate:
    jobs:
      - validate
      - terratest-11
      - terratest-12
