jobs:
  terratest:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      environment:
      - TEST_RESULTS: /tmp/test-results
      image: trussworks/circleci:6986bb9022e5a83599feb66a7128a2d0fa12732a
    steps:
    - checkout
    - restore_cache:
        keys:
        - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        - go-mod-sources-v1-{{ checksum "go.sum" }}-{{ checksum "bin/check-go-version"
          }}
    - run:
        command: 'echo ''export PATH=${PATH}:~/go/bin'' >> $BASH_ENV

          source $BASH_ENV

          '
        name: Adding go binaries to $PATH
    - run: go get github.com/jstemmer/go-junit-report
    - run:
        command: "temp_role=$(aws sts assume-role \\\n        --role-arn arn:aws:iam::313564602749:role/circleci\
          \ \\\n        --role-session-name circleci)\nexport AWS_ACCESS_KEY_ID=$(echo\
          \ $temp_role | jq .Credentials.AccessKeyId | xargs)\nexport AWS_SECRET_ACCESS_KEY=$(echo\
          \ $temp_role | jq .Credentials.SecretAccessKey | xargs)\nexport AWS_SESSION_TOKEN=$(echo\
          \ $temp_role | jq .Credentials.SessionToken | xargs)\nmake test\n"
        name: Assume role and run terratest
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
        - ~/.cache
    - save_cache:
        key: go-mod-sources-v1-{{ checksum "go.sum" }}-{{ checksum "bin/check-go-version"
          }}
        paths:
        - ~/go/pkg/mod
    - store_test_results:
        path: /tmp/test-results/gotest
references:
  circleci: trussworks/circleci:6986bb9022e5a83599feb66a7128a2d0fa12732a
version: 2.1
workflows:
  validate:
    jobs:
    - terratest:
        context:
        - org-global
  version: 2.1
